server:
  servlet:
    context-path: /

spring:
  servlet:
    #文件大小配置
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
  jackson:
    #时区设置
    time-zone: GMT+8
  #liquibase配置
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  #数据库配置
  datasource:
    url: jdbc:mysql://172.18.50.13:3306/mc_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: messagecenter
    password: p@ssw@rd123
  #redis配置
  redis:
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 1000
        max-wait: -1
    sentinel:
      nodes: 172.19.50.106:26379,172.18.50.13:26379,172.19.50.178:26379
      master: mymaster
    password: soa@#324Ssd11

## 日志打印级别
logging:
  level:
    com.movitech: DEBUG
    com.alibaba.nacos.client.naming : error
  config: classpath:logback-custom.xml

## 日志输入路径
log:
  sysPath: ./log
  operatePath: ./log
  maxFileSize: 100MB
  maxHistory: 15

## 平台自定义参数
platform:
  #分页参数配置
  pagination:
    maxPageSize: 2000
    pageSize: 20

#tk.mybatis配置
mapper:
  safeDelete: true
  safeUpdate: true
  enableMethodAnnotation: true

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#redis配置
custom:
  redis:
    prefix: Project_


ribbon:
  #  OkToRetryOnAllOperations: true #对所有操作请求都进行重试,默认false
  ReadTimeout: 50000   #负载均衡超时时间，默认值5000,ribbon读取超时时间长
  ConnectTimeout: 30000 #ribbon请求连接的超时时间，默认值2000,ribbon链接超时时长
  MaxAutoRetries: 1     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #断路器超时时间，默认1000ms

feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  httpclient:
    enabled: true

remoteServer:
  mcServer:
    serverName: MessageService2
    serverUrl:
  infusionServer:
    serverName: InfusionService
    serverUrl: